apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app-deployment
  labels:
    app: book-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app
          image: book-review-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: book-app-config
            - secretRef:
                name: book-app-secrets
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: book-app-data-pvc